---
abstract: 'Tool to have #! dispatch to the best executable for the job.'
author:
  - 'Chad Granum <exodist7@gmail.com>'
build_requires:
  Test::Simple: 0.88
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.4204, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Dispatch
provides:
  App::Dispatch:
    file: lib/App/Dispatch.pm
    version: 0.007
resources:
  bugtracker: http://github.com/exodist/App-Dispatch/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/exodist/App-Dispatch
version: 0.007
